spring:
  undertow:
    threads:
      io: 16
      worker: 256
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
    initialization-mode: always
    data:
#      - classpath:schema.sql
#      - classpath:init_role.sql
  jpa:
    show-sql: true
    generate-ddl: false
    database: mysql
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
  flyway:
    jpa:
      enabled: true
    baseline-on-migrate: true
    enabled: true
    locations: classpath:/db/migration
    baseline-version: 1
  aws:
    region: ap-northeast-2
    bucket: sparcs-2023-startup-hackathon-p-2
    url: s3://sparcs-2023-startup-hackathon-p-2/
  profiles:
    active: prod # local, prod

springdoc:
  swagger-ui:
    operations-sorter: method
    config-url: /api-docs
    disable-swagger-default-url: false
  api-docs:
    path: /api-docs

springfox:
  documentation:
    swagger:
      v2:
        path: /v2/api-docs

jwt-security:
  expiration-time: 365
